language: cpp

sudo: required

notification:
  email: false

branches:
  only: 
    - master
    - stable

before_install:
  - sudo apt-get update -qq
  - mkdir build
  - make download-all
  - sudo ./install_prereqs.sh ubuntu
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install --upgrade distribute --cache-dir=$HOME/.pip-cache
  - pip install --upgrade -r externals/iris/python_requirements.txt --cache-dir=$HOME/.pip-cache
  - make

script:
  - cd drake/pod-build
  - ctest -j 1 -D Experimental -C $BUILD_TYPE --output-on-failure --timeout 1000 --track Continuous

# The compiler and env:matrix options create an matrix of build configurations (gcc + Release, gcc + Debug, clang + Release, clang + Debug)

compiler:
  - gcc
  - clang

env:
  global:
    - CMAKE_FLAGS="-DWITH_SPOTLESS:BOOL=OFF -DWITH_MOSEK:BOOL=ON -DWITH_IRIS:BOOL=ON"
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release